[GLOBAL]
pants_version = "2.14.0"

use_deprecated_pex_binary_run_semantics = false

backend_packages.add = [
  "pants.backend.python",
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = [">=3.8, <3.9"]
enable_resolves = true

[python.resolves]
  lab = "3rdparty/python/lab.lock"
  default = "3rdparty/python/default.lock"

