[GLOBAL]
pants_version = "2.14.0"

backend_packages.add = [
  "pants.backend.python",
  "pants.backend.python.typecheck.mypy",
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = [">=3.7"]
enable_resolves = true

[python.resolves]
  lab = "3rdparty/python/lab.lock"
  default = "3rdparty/python/default.lock"

[mypy]
  version = "mypy==0.910"
  lockfile = "3rdparty/python/mypy.lock"
